export enum TypeReport {
    FACTURE_PROFORMA = "factureProforma",
    POLICE = "POLICE",
    AVENANT_INCORPORATION = 'AVENANT_INCORPORATION',
    AVENANT_RETRAIT = 'AVENANT_RETRAIT',
    LISTE_INCORPORATION = 'LISTE_INCORPORATION',
    LISTE_RETRAIT = 'LISTE_RETRAIT',
    FACTURE_INCORP = 'FACTURE_INCORP',
    }
