export enum TypeReport {
    FACTURE_PROFORMA = "factureProforma",
    POLICE = "POLICE",
    AVENANT_INCORPORATION = 'AVENANT_INCORPORATION',
    AVENANT_RETRAIT = 'AVENANT_RETRAIT',
    LISTE_INCORPORATION = 'LISTE_INCORPORATION',
    LISTE_RETRAIT = 'LISTE_RETRAIT',
    FACTURE_INCORP = 'FACTURE_INCORP',
    AFAIRE_NOUVELLE = 'AFAIRE_NOUVELLE',
    LISTE_AFAIRE_NOUVELLE = 'LISTE_AFAIRE_NOUVELLE',
    AVENANT_RENOUVELLEMENT = 'AVENANT_RENOUVELLEMENT',
    LISTE_AVENANT_RENOUVELLEMENT = 'LISTE_AVENANT_RENOUVELLEMENT'
    }
