import {props, createAction} from '@ngrx/store';
import { Rapport } from '../police/model';
import { Groupe, GroupeList } from './model';
export const createGroupe = createAction('[App Init] Create Groupe', props<Groupe>());
export const updateGroupe = createAction('[App Init] update Groupe', props<Groupe>());
export const deleteGroupe = createAction('[App Init] delete Groupe', props<Groupe>());
export const deleteGroupes = createAction('[App Init] delete Groupes', props<{groupeList: Array<Groupe>}>());
export const loadGroupe = createAction('[App Init] load Groupe', props<{policeId: string}>());
export const setGroupe = createAction('[App Init] set Groupe',  props<GroupeList>());
export const importGroupe = createAction('[App Init] import Groupe',  props<{file: File}>());
export const loadRapport = createAction('[App Init] load Rapport groupe', props<Groupe>());
export const setRapport = createAction('[App Init] set Rapport Statistique groupe', props<Rapport>());
export const createGroupeRenouvAndModif = createAction('[App Init] Create Groupe Renouv and Modif', props<{groupe: Groupe, avenantId: string}>());
